### PR TITLE
Reorganize discrete model

### PR DESCRIPTION
**Pull request by WardBrian**
Binomial models require special handling since their data is a different shape. I think this is worthy of their own stan model.

This is not currently fully implemented; data validation needs an overhaul, as does testing. That said, it was broken before, too.

### CODE REVIEW

**Comment by bob-carpenter** [comment]
There are two kinds of data, random data, which we model, and constants, which we don't.  For the binomial, the modeled data is just a sequence of counts, so it's just an $N$-vector of natural numbers $y_1, ..., y_N$.  The binomial also requires $N$ constants, $M_1, ..., M_N$, which we do not model.  The model for the data $y$ is then

$y_n \sim \textrm{binomial}(M_n, \textrm{logit}^{-1}(x_n \cdot \beta))$

**Comment by WardBrian** [comment]
Yes, I didn’t mean different data in a modeling sense, but rather in an API sense. The user needs to supply those constants somehow. The options are either have the user supply a 2xN matrix for y (I believe this is what rstanarm does) or as an additional keyword argument (I believe this makes more sense for a scikit API, since if we accepted a 2d y, by the contract our `predict` would have to _produce_ a 2d y, which would mean either storing or somehow generating new versions of those constants)

**Comment by bob-carpenter** [comment]
> if we accepted a 2d y, by the contract our predict would have to produce a 2d y,

Perfect---this is the key distinction I was trying to highlight between constants and modeled data.  The Gelman and Hill regression book has a nice table of different kinds of variables in Bayesian models, which I tried to follow in the Stan doc.

**Comment by WardBrian** [comment]
Yes, we're on the same page there. The next step/question I have is whether it makes sense to spin Binomial models off as a separate Python object as well, or if the GLM functions should accept a keyword argument which is only valid for `family="binomial"`. 

I'm torn on this, since having it as a separate class is odd in one way ("Why are all the families of GLM part of `GLM()`, except for binomial which is its own `BinomialGLM()`?"), but having keyword arguments which rely on previous options is a slippery slope of complexity.

**Comment by bob-carpenter** [comment]
I really don't like keywords that depend on other options.  That's been my biggest point of disagreement with the interface designs other than CmdStan.   I'd much rather see the constants included with the predictors `x` than with the modeled variables `y`.

It's absolutely conventional in R, but they don't do a lot of error checking and instead try to guess what the user wants from what they input (see example below).  

```
dgamma(x, shape, rate = 1, scale = 1/rate, log = FALSE)

rate | an alternative way to specify the scale.
shape, scale | shape and scale parameters. Must be positive, scale strictly.
```

And the doc doesn't say what happens if you specify both scale and rate!  In fact, R never tries to keep anything consistent.  You can edit fields of the output of the linear regression estimator `lm` to make the fit inconsistent with the data or model specification without a hint of complaint.

**Pull request merged**
